# Generated by Django 4.1.2 on 2024-10-20 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_category_name_planter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Planter',
        ),
    ]
