# Generated by Django 4.1.2 on 2024-10-20 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_delete_planter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('size', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=30)),
                ('material', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, default='path/to/default/image.jpg', null=True, upload_to='products/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
    ]
