# Generated by Django 4.1.2 on 2024-10-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_planter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planter',
            name='image',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
