# Generated by Django 4.1.2 on 2024-10-21 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_planter_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planter',
            name='image',
        ),
    ]
