# Generated by Django 4.1.2 on 2024-10-21 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_planter_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Planter',
        ),
    ]
